"""empty message

Revision ID: 14697336d5d6
Revises: 9e1c7c7dd831
Create Date: 2023-08-30 13:55:31.347884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14697336d5d6'
down_revision = '9e1c7c7dd831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('personajes_id', sa.Integer(), nullable=True),
    sa.Column('vehiculos_id', sa.Integer(), nullable=True),
    sa.Column('planetas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personajes_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['planetas_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehiculos_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito')
    # ### end Alembic commands ###
