"""empty message

Revision ID: bf392699c697
Revises: 27efa6b704ba
Create Date: 2023-08-29 19:17:07.875426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf392699c697'
down_revision = '27efa6b704ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('vehicle_class', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=False),
    sa.Column('cost_in_credits', sa.String(length=120), nullable=False),
    sa.Column('length', sa.String(length=120), nullable=False),
    sa.Column('crew', sa.String(length=120), nullable=False),
    sa.Column('passengers', sa.String(length=120), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=120), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=120), nullable=False),
    sa.Column('consumables', sa.String(length=120), nullable=False),
    sa.Column('films', sa.String(length=120), nullable=False),
    sa.Column('pilots', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cargo_capacity'),
    sa.UniqueConstraint('consumables'),
    sa.UniqueConstraint('cost_in_credits'),
    sa.UniqueConstraint('crew'),
    sa.UniqueConstraint('films'),
    sa.UniqueConstraint('length'),
    sa.UniqueConstraint('manufacturer'),
    sa.UniqueConstraint('max_atmosphering_speed'),
    sa.UniqueConstraint('model'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('passengers'),
    sa.UniqueConstraint('pilots'),
    sa.UniqueConstraint('vehicle_class')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
